### ISSUE TITLE
Spotify Getting Corrupt After Installing

### ISSUE THREAD

**Issue by abhigyanj** [Nuzair46/BlockTheSpot-Mac#71]

**Comment by 0f7b90** [comment]
Me too

**Comment by abhigyanj** [comment]
I've tried

**Comment by Nuzair46** [comment]
Please post the screenshot of you patching it.

**Comment by abhigyanj** [comment]
![image](https://github.com/Nuzair46/SpotX-Mac/assets/76672257/e52f6094-c1c3-4b39-88d4-b324dc83bb1c)

**Comment by bombastiik** [comment]
bro it crashes did the dev abandon the project can someone fork im getting tired of these ads

**Comment by 0f7b90** [comment]
Try: bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -hu

**Comment by abhigyanj** [comment]
Still doesn't work

**Comment by FlyMeToTheMoonAndLetMePlayAmongTheStars** [comment]
I had a similar issue where Spotify would not open because it was "corrupted". 

I deleted Spotify from Applications in Finder, then re-installed the app and ran the script, now everything seems to work perfectly fine.

**Comment by InternetRodent** [comment]
> I had a similar issue where Spotify would not open because it was "corrupted".
> 
> I deleted Spotify from Applications in Finder, then re-installed the app and ran the script, now everything seems to work perfectly fine.

Thanks, this worked for me!

**Comment by luchianneos** [comment]
> I had a similar issue where Spotify would not open because it was "corrupted".
> 
> I deleted Spotify from Applications in Finder, then re-installed the app and ran the script, now everything seems to work perfectly fine.

I tried re-installing the applicazione multiple times but I still get the error after applying the patch, seems to be related to code signing

```
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000103db4a43
Exception Codes:       0x0000000000000032, 0x0000000103db4a43

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page
```

**Comment by bombastiik** [comment]
Reinstalling does not work for me either

**Comment by Nuzair46** [comment]
Will look into this soon. Sorry for the delay.

**Comment by Nuzair46** [comment]
Fixed with latest patch

**Comment by bombastiik** [comment]
<img width="572" alt="image" src="https://github.com/Nuzair46/BlockTheSpot-Mac/assets/152789490/d028a420-0d68-46f7-9d2a-8da9b423da6e">

**Comment by Nuzair46** [comment]
@bombastiik #75 please report there
