### ISSUE TITLE
Sponsored Listing Tag Displaying

### ISSUE THREAD

**Issue by jimmysofat6864** [Nuzair46/BlockTheSpot-Mac#73]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

United States

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel)
1.2.20.1216.ge7a7b92f
- macOS: 12.6.8
- Shell: zsh
```

### 📝 Description

1. Install Spotify
2. Run Patch on latest version
3. View top of homepage on launch with the ad remnants.

### 🖥️ Terminal Input/Output

~ % bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh) -f

************************
SpotX-Mac by @Nuzair46
************************

Spotify version: 1.2.20.1216
SpotX-Mac version: 1.2.22.982

Backup found, restoring original...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Removing logging...
Rebuilding xpui...
Signing Spotify...
SpotX finished patching!

### 📸 Screenshots

<img width="1011" alt="Screen Shot 2023-12-16 at 11 44 46 PM" src="https://github.com/Nuzair46/SpotX-Mac/assets/69532417/62958adc-4f56-4e0e-baf5-281a5a4910f2">

**Comment by Nuzair46** [comment]
Fixed with latest release
