### ISSUE TITLE
UX showing blank screen

### ISSUE THREAD

**Issue by Amiir97** [Nuzair46/BlockTheSpot-Mac#74]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and SpotX

### Сountry of your account

Canada

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel) 1.2.30.1135.g02fef27a
- macOS: 10.15.7
- Shell: bash
```

### 📝 Description

1. Quit Spotify
2. Insert install command in terminal: bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh)
3. Open Spotify
4. Only see a blank window as attached below. Clicking on menu such as File or Edit or View at the top menu bar is responsive but does not load a new window. For example, nothing happens when I click About Spotify from menu bar.

### 🖥️ Terminal Input/Output

bash <(curl -sSL https://raw.githubusercontent.com/SpotX-CLI/SpotX-Mac/main/install.sh)

************************
SpotX-Mac by @Nuzair46
************************

Spotify version: 1.2.30.1135
SpotX-Mac version: 1.2.22.982

Creating backup...
Extracting xpui...
Applying SpotX patches...
Removing ad-related content...
Removing premium-only features...
Removing logging...
Rebuilding xpui...
Signing Spotify...
SpotX finished patching!

### 📸 Screenshots

![Screen Shot 2024-02-03 at 3 54 37 PM](https://github.com/Nuzair46/SpotX-Mac/assets/15268892/2b77b9b4-faef-40ab-af55-642ee4d0d222)

**Comment by BillyData** [comment]
Same here, also black UI

**Comment by erenmlbb** [comment]
same here..... songs still plays though

**Comment by raffidil** [comment]
Same here

**Comment by AO2233** [comment]
SAME HERE
```
----------
JUST DOWNGRADE
----------
this old version(1.2.26.1187) can still be worked.
```


https://spotify.en.uptodown.com/mac/versions

<img width="1920" alt="image" src="https://github.com/Nuzair46/SpotX-Mac/assets/139159361/671d17dc-1eed-42e5-9bcb-5057759239d2">

**Comment by BillyData** [comment]
> @Amiir97 @raffidil @Parth2209 @BillyData @erenmlbb
> 
> ### SAME HERE, 2 ways to slove it.
> ## 1. use SpotX-Official/SpotX-Bash (recommend)
> https://github.com/SpotX-Official/SpotX-Bash
> 
> ## 2. JUST DOWNGRADE
> ```
> ----------
> JUST DOWNGRADE
> ----------
> this old version(1.2.26.1187) can still be worked.
> ```
> 
> https://spotify.en.uptodown.com/mac/versions
> 
> <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/139159361/302244376-671d17dc-1eed-42e5-9bcb-5057759239d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxODM0NDUsIm5iZiI6MTcwNzE4MzE0NSwicGF0aCI6Ii8xMzkxNTkzNjEvMzAyMjQ0Mzc2LTY3MWQxN2RjLTFlZWQtNDJlNS05YmNiLTUwNTc3NTkyMzlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwMTMyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2JkNjlkMWE1MzU0YTE3ZDEwODRkMzgyMTI4N2Q4YmY2Y2Q1Yzc3Yjc0MTI5YmRhODI5MWM5MTNlODA3ODAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.feXTCHsJqPYbgu4zF5IWpLhhzxq5uGtzOwtbLys7a3g">

This works, thanks a lot

**Comment by m1daz** [comment]
Same

**Comment by webenadam** [comment]
Same here

**Comment by donqee** [comment]
> @Amiir97 @raffidil @Parth2209 @BillyData @erenmlbb
> 
> ### SAME HERE, 2 ways to slove it.
> ## 1. use SpotX-Official/SpotX-Bash (recommend)
> https://github.com/SpotX-Official/SpotX-Bash
> 
> ## 2. JUST DOWNGRADE
> ```
> ----------
> JUST DOWNGRADE
> ----------
> this old version(1.2.26.1187) can still be worked.
> ```
> 
> https://spotify.en.uptodown.com/mac/versions
> 
> <img alt="image" width="1920" src="https://private-user-images.githubusercontent.com/139159361/302244376-671d17dc-1eed-42e5-9bcb-5057759239d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDMxMjMsIm5iZiI6MTcwNzU0MjgyMywicGF0aCI6Ii8xMzkxNTkzNjEvMzAyMjQ0Mzc2LTY3MWQxN2RjLTFlZWQtNDJlNS05YmNiLTUwNTc3NTkyMzlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQwNTI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTZlMjY4NGIyOTU1ODlhOWE3MDhiNzBkZjU3NjRkMjlhZTlmNmIyNGFkZTMxZGEyN2JjNzYxZWYwMDdkNTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qCax_TGYnkfaKUbPA4pNS8H6i8bLmlz69mDGHhFhorE">

This works, thanks a lot

**Comment by Nuzair46** [comment]
Fixed with latest release

**Comment by Amiir97** [comment]
Thank you!
