### ISSUE TITLE
Incompatible with Spotify for macOS (Apple Silicon) 1.2.32.997.g4c6498b6

### ISSUE THREAD

**Issue by sybercorp** [Nuzair46/BlockTheSpot-Mac#76]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of Spotify and BlockTheSpot

### Сountry of your account

United States

### What is your Spotify Plan?

Premium

### Do you have Spicetify installed?

No

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Apple Silicon) 1.2.32.997.g4c6498b6
- macOS: 14.3.1 (23D60)
- Shell: zsh
```

### 📝 Description

The most recent Spotify update is not compatible with the most recent release of BlockTheSpot-Mac, and attempting to run the BlockTheSpot-Mac installation script results in errors stating such.

### 🖥️ Terminal Input/Output

```
************************
BlockTheSpot-Mac by @Nuzair46
************************

Spotify version: 1.2.32.997
BlockTheSpot-Mac version: 1.2.30.1135

This version of BlockTheSpot-Mac is not compatible with your Spotify version.
Pleas use an older version of BlockTheSpot-Mac or update Spotify.
```

**Comment by luisinostrozaf** [comment]
what i did to solve this: 
1) uninstall Spotify 
2) reinstall Spotify 
3) close Spotify 
4) run the bash command in terminal. 
Let me know if that worked for you.

**Comment by sybercorp** [comment]
> what i did to solve this:
> 
> 1. uninstall Spotify
> 2. reinstall Spotify
> 3. close Spotify completely
> 4. run the bash command in terminal.
> 
> Let me know if that worked for you.

That's likely because when you reinstall Spotify from the most recent installer on their website, it installs 1.2.31, not 1.2.32.  1.2.31 is compatible with BlockTheSpot while 1.2.32 is not (as I said in the original post).

As you can see, after uninstalling/reinstalling (which I said I had already done in the original post), BlockTheSpot installs just fine... but that's because Spotify is still at 1.2.31.  After updating Spotify to the current release (again, which does NOT get installed by their installer despite being the most recent installer available on their website), BlockTheSpot is no longer compatible.

************************
BlockTheSpot-Mac by @Nuzair46
************************

Spotify version: 1.2.31.1205
BlockTheSpot-Mac version: 1.2.30.1135

Creating backup...
Extracting xpui...
Applying BlockTheSpot patches...
Removing ad-related content...
Patching Binary...
Removing premium-only features...
Removing logging...
Adding credits...
Signing Spotify...
BlockTheSpot finished patching!

<redacted> bash <(curl -sSL https://raw.githubusercontent.com/Nuzair46/BlockTheSpot-Mac/main/install.sh)

************************
BlockTheSpot-Mac by @Nuzair46
************************

Spotify version: 1.2.32.997
BlockTheSpot-Mac version: 1.2.30.1135

This version of BlockTheSpot-Mac is not compatible with your Spotify version.
Pleas use an older version of BlockTheSpot-Mac or update Spotify.

**Comment by janlorenzn** [comment]
Howdy, I think I found as a solution. After installing Spotify 1.2.31.1135 from Spotify's website, I was also experiencing the unexpected shutdown issue. The way I resolved it was by after doing a clean install of Spotify, I searched and found the Spotify application on my mac, and then dragged it to the applications folder (because it was not showing up there before). I then reran the BlockTheSpot command in terminal and Spotify was able to launch correctly

`- Spotify: Spotify for macOS (Apple Silicon) 1.2.31.1205.g4d59ad7c
- macOS: 14.3.1
- Shell: zsh`

**Comment by sybercorp** [comment]
> Howdy, I think I found as a solution. After installing Spotify 1.2.31.1135 from Spotify's website, I was also experiencing the unexpected shutdown issue. The way I resolved it was by after doing a clean install of Spotify, I searched and found the Spotify application on my mac, and then dragged it to the applications folder (because it was not showing up there before). I then reran the BlockTheSpot command in terminal and Spotify was able to launch correctly
> 
> ```
> - Spotify: Spotify for macOS (Apple Silicon) 1.2.31.1205.g4d59ad7c
> - macOS: 14.3.1
> - Shell: zsh
> ```

What does that have to do with BlockTheSpot being incompatible with Spotify 1.2.32 ?

**Comment by lacorde** [comment]
Just install Spotify 1.2.31 while waiting for an update.
https://spotify.en.uptodown.com/mac/versions

**Comment by Nuzair46** [comment]
Fixed

**Comment by inboxcda** [comment]
> Just install Spotify 1.2.31 while waiting for an update. https://spotify.en.uptodown.com/mac/versions

God bless your beautiful souls for the steps and for providing a link to the dmg I needed. That solved my problem.
@luisinostrozaf @lacorde
