### ISSUE TITLE
Not playing song

### ISSUE THREAD

**Issue by wbaak** [Nuzair46/BlockTheSpot-Mac#78]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [x] I did a clean install of Spotify and BlockTheSpot

### Сountry of your account

Germany

### What is your Spotify Plan?

Free

### Do you have Spicetify installed?

Yes

### ℹ Computer information

```markdown
- Spotify: Spotify for macOS (Intel) 1.2.32.997.g4c6498b6
- macOS: Sonoma Version 14.3.1
- Shell: zsh
```

### 📝 Description

1. installation works (no ads in spotify)
2. loads very slowly or not at all, tracks do not start (equaliser symbol moving but track stays at 0:00)

### 🖥️ Terminal Input/Output

************************
BlockTheSpot-Mac by @Nuzair46
************************

Spotify version: 1.2.32.997
BlockTheSpot-Mac version: 1.2.32.985.g3be2709c

Creating backup...
Extracting xpui...
Applying BlockTheSpot patches...
Removing ad-related content...
Patching Binary...
Removing premium-only features...
Removing logging...
Adding credits...
Signing Spotify...
BlockTheSpot finished patching!

### 📸 Screenshots

<img width="787" alt="image" src="https://github.com/Nuzair46/BlockTheSpot-Mac/assets/87698324/1fab7343-140e-426c-a161-6c6b5df1ab13">

<img width="891" alt="image" src="https://github.com/Nuzair46/BlockTheSpot-Mac/assets/87698324/0a8aa603-040a-457a-9a3d-c3f4bd23a466">

**Comment by Nuzair46** [comment]
try uninstalling the patch and see if problem still persists

**Comment by wbaak** [comment]
thanks!  tried it several times already with no luck! tried installation with different arguments and with restarting after installation. same results

**Comment by Nuzair46** [comment]
This looks like an issue with Spotify. closing
